project_id = "qcxbeqgcsfjkketstwtf"

[functions.send-cart-notification]
verify_jwt = false

[functions.checkout-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
